import { ACHIEVEMENTS, CATEGORIES, CAT_ORDER, STAT_NAMES, TIERS } from "../game/constants";
import { calcStreak, getRankBadge, getRankTitle, xpNeed } from "../game/rules";

/* ═══════════════════════════════════════════════════════════════════════════
   Markdown generation for Obsidian export.

   Every note carries YAML frontmatter so the vault can query across them —
   that's the whole point of exporting rather than screenshotting.
   ═══════════════════════════════════════════════════════════════════════════ */

export function generateDailyNote(data, todayKey) {
  const streak    = calcStreak(data.dailyLog, data.shieldedDays);
  const need      = xpNeed(data.level);
  const todayLog  = data.dailyLog?.[todayKey] || { xp: 0, quests: 0 };
  const doneIds   = new Set(Object.keys(data.done));
  const daily     = data.quests.filter((q) => q.repeat !== "once");
  const onceQ     = data.quests.filter((q) => q.repeat === "once");
  const todayHist = data.history.filter((h) => h.t.startsWith(todayKey));

  const lines = [
    `---`,
    `tags: [rpg-productivity, daily-journal]`,
    `date: ${todayKey}`,
    `hunter: "${data.name}"`,
    `level: ${data.level}`,
    `streak: ${streak}`,
    `xp_today: ${todayLog.xp}`,
    `---`,
    ``,
    `# Hunter's Journal — ${todayKey}`,
    ``,
    `## Status`,
    `- **Level:** ${data.level} — ${getRankTitle(data.level)}`,
    `- **EXP:** ${data.xp} / ${need} (${Math.round((data.xp / need) * 100)}%)`,
    `- **Streak:** ${streak} day${streak !== 1 ? "s" : ""} 🔥`,
    `- **XP Earned Today:** ${todayLog.xp}`,
    ``,
  ];

  if (daily.length > 0) {
    lines.push(`## Daily Quests`);
    daily.forEach((q) => {
      const done = doneIds.has(q.id);
      const xp   = TIERS[q.tier || "E"].xp;
      const stat = CATEGORIES[q.category]?.stat || "";
      lines.push(`- [${done ? "x" : " "}] **${q.name}** +${xp} EXP · ${stat} [${q.tier || "E"}]${q.desc ? ` — *${q.desc}*` : ""}`);
    });
    lines.push(``);
  }

  if (onceQ.length > 0) {
    lines.push(`## One-Time Quests`);
    onceQ.forEach((q) => {
      const done = doneIds.has(q.id);
      const xp   = TIERS[q.tier || "E"].xp;
      const stat = CATEGORIES[q.category]?.stat || "";
      lines.push(`- [${done ? "x" : " "}] **${q.name}** +${xp} EXP · ${stat} [${q.tier || "E"}]`);
    });
    lines.push(``);
  }

  lines.push(`## Attributes`);
  lines.push(`| Stat | Name | Value |`);
  lines.push(`| ---- | ---- | ----- |`);
  Object.entries(data.stats).forEach(([k, v]) => lines.push(`| ${k} | ${STAT_NAMES[k]} | ${v} |`));
  lines.push(``);

  if (todayHist.length > 0) {
    lines.push(`## Combat Log`);
    todayHist.forEach((h) => {
      const time = new Date(h.t).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      lines.push(`- ${time} — **${h.name}** +${h.xp} EXP (${h.stat}) [${h.tier}]`);
    });
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by Hunter's Journal*`);
  return lines.join("\n");
}

export function generateHunterProfile(data) {
  const streak      = calcStreak(data.dailyLog, data.shieldedDays);
  const need        = xpNeed(data.level);
  const totalXp     = Object.values(data.dailyLog).reduce((a, b) => a + b.xp, 0);
  const totalQuests = Object.values(data.dailyLog).reduce((a, b) => a + b.quests, 0);
  const bestDay     = Math.max(0, ...Object.values(data.dailyLog).map((d) => d.quests));

  const lines = [
    `---`,
    `tags: [rpg-productivity, hunter-profile]`,
    `hunter: "${data.name}"`,
    `rank: "${getRankBadge(data.level)}"`,
    `level: ${data.level}`,
    `---`,
    ``,
    `# Hunter Profile: ${data.name}`,
    ``,
    `## Identity`,
    `| Field | Value |`,
    `| ----- | ----- |`,
    `| Name | ${data.name} |`,
    `| Rank Title | ${getRankTitle(data.level)} |`,
    `| Badge | **${getRankBadge(data.level)}** |`,
    `| Level | ${data.level} |`,
    `| EXP | ${data.xp} / ${need} |`,
    `| Streak | ${streak} days |`,
    ``,
    `## Attributes`,
    `| Stat | Name | Value |`,
    `| ---- | ---- | ----- |`,
    ...Object.entries(data.stats).map(([k, v]) => `| ${k} | ${STAT_NAMES[k]} | ${v} |`),
    ``,
    `## Lifetime Stats`,
    `| Metric | Value |`,
    `| ------ | ----- |`,
    `| Total XP Earned | ${totalXp} |`,
    `| Total Quests Completed | ${totalQuests} |`,
    `| Active Days | ${Object.keys(data.dailyLog).length} |`,
    `| Best Day | ${bestDay} quests |`,
    ``,
  ];

  if (data.achievements?.length > 0) {
    lines.push(`## Achievements (${data.achievements.length} / ${ACHIEVEMENTS.length})`);
    ACHIEVEMENTS.forEach((a) => {
      const unlocked = data.achievements.includes(a.id);
      lines.push(`- [${unlocked ? "x" : " "}] ${a.icon} **${a.label}** — ${a.desc}`);
    });
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by Hunter's Journal*`);
  return lines.join("\n");
}

export function generateQuestArchive(data) {
  const lines = [
    `---`,
    `tags: [rpg-productivity, quest-archive]`,
    `hunter: "${data.name}"`,
    `total_quests: ${data.quests.length}`,
    `---`,
    ``,
    `# Quest Archive — ${data.name}`,
    ``,
  ];

  const byCategory = {};
  data.quests.forEach((q) => {
    if (!byCategory[q.category]) byCategory[q.category] = [];
    byCategory[q.category].push(q);
  });

  CAT_ORDER.forEach((catKey) => {
    const quests = byCategory[catKey];
    if (!quests?.length) return;
    const cat = CATEGORIES[catKey];
    lines.push(`## ${cat.label} (${cat.stat})`);
    quests.forEach((q) => {
      const xp     = TIERS[q.tier || "E"].xp;
      const repeat = q.repeat === "daily" ? "Daily" : q.repeat === "weekly" ? "Weekly" : "Once";
      lines.push(`### ${q.name}`);
      lines.push(`- **Tier:** ${q.tier || "E"} (+${xp} XP)`);
      lines.push(`- **Repeat:** ${repeat}`);
      if (q.desc) lines.push(`- **Description:** ${q.desc}`);
      lines.push(``);
    });
  });

  if (data.history.length > 0) {
    lines.push(`## Recent History`);
    lines.push(`| Date | Quest | XP | Stat | Tier |`);
    lines.push(`| ---- | ----- | -- | ---- | ---- |`);
    data.history.slice(0, 25).forEach((h) => {
      const d   = new Date(h.t);
      const ts  = d.toLocaleDateString("en-CA") + " " + d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      lines.push(`| ${ts} | ${h.name} | +${h.xp} | ${h.stat} | ${h.tier} |`);
    });
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by Hunter's Journal*`);
  return lines.join("\n");
}

/* With a vault name we hand off via the obsidian:// protocol so the note lands
   in place; without one we fall back to a plain download. */
export function exportToObsidian(content, filePath, vaultName) {
  const vault = vaultName?.trim();
  if (vault) {
    const uri = `obsidian://new?vault=${encodeURIComponent(vault)}&file=${encodeURIComponent(filePath)}&content=${encodeURIComponent(content)}`;
    window.open(uri, "_self");
  } else {
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = filePath.split("/").pop() + ".md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
